### ISSUE TITLE
Crawlarr is being flagged as a bot

### ISSUE THREAD

**Issue by SomeRandom-Dev** [LockBlock-dev/crawlarr#1]
Hello,
Crawlarr appears to not follow redirects (for example https://amazon.de -> https://www.amazon.de but the scan would result in an empty link list).
If this could be an option in the config or default it would be much appreciated.

**Comment by LockBlock-dev** [comment]
Hey thanks for using Crawlarr!
The net/http lib is following the redirects, the problem here is Amazon flagging the crawler as a bot and blocking it. You might need a headless browser to bypass this.
